# Generated by Django 4.0.1 on 2022-01-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage_image', models.ImageField(upload_to='homepage_images/')),
                ('homepage_text', models.CharField(max_length=300)),
            ],
        ),
    ]
